version: '3.8'
services:
  db:
    image: pgrouting/pgrouting:16-3.4-3.6.1
    ports:
      - 54321:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: vaylaopas
      POSTGRES_USER: vaylaopas
      POSTGRES_PASSWORD: vaylaopas
  openmaptiles:
    image: maptiler/tileserver-gl:latest
    ports:
      - 8000:80
    volumes:
      - ./resources/openmaptiles:/data
    command: --silent
