name: CI

on: [push]

env:
  NODE_VERSION: 12.18.3

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        uses: ktmud/cached-dependencies@v1

      - name: Run tests
        run: |
          npm run lint
          npm run test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        uses: ktmud/cached-dependencies@v1

      - name: Build
        run: |
          npm run build
